# MARK: - Связь с документацией: Документация проекта (Версия: 1.0.0). Статус: Синхронизировано.

disabled_rules:
  - test_configuration_builder

opt_in_rules:
  - empty_count
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - last_where
  - modifier_order
  - redundant_nil_coalescing
  - line_length
  - cyclomatic_complexity
  - function_body_length
  - type_body_length
  - file_length
  - implicitly_unwrapped_optional
  - force_unwrapping:
      excluded:
        - ChatTests
        - ChatUITests
  - missing_docs
  - non_optional_string_data_conversion
  - optional_data_string_conversion:
      excluded:
        - "**/ChatUITests/**"
  - vertical_whitespace_closing_braces
  - identifier_name
  - trailing_whitespace
  - vertical_whitespace

line_length: 160

# Лимиты для предотвращения "километровых файлов"
file_length: 150

function_body_length: 20

type_body_length: 100

identifier_name:
  min_length: 2
  excluded:
    - id

custom_rules:
  no_direct_color_use:
    name: "No direct color use"
    regex: 'Color\(\.[a-zA-Z]+\)'
    message: "Use AppColors or SwiftGen constants instead of direct Color extensions"
    severity: error

  no_print_logger:
    name: "No print()"
    # Запрещаем print(), кроме строк содержащих разрешенные контексты (#Preview | Logger | metrics.csv)
    regex: '^(?!.*(#Preview|Logger|metrics\.csv)).*print\('
    message: "Use Logger (Pulse) instead of print(); allowed only in #Preview, Logger proxy calls, or metrics.csv writes"
    severity: error
    excluded: "Tools/Scripts/.*"

  viewmodel_main_actor:
    name: "ViewModel MainActor"
    regex: '(?m)\A(?![\s\S]*@MainActor)[\s\S]*class\s+\w+ViewModel'
    message: "ViewModel classes must be marked with @MainActor"
    severity: error

  doc_link_required:
    name: "Missing Doc Link"
    regex: '(?m)\A(?![\s\S]*MARK: - Связь с документацией:)'
    message: "Missing Documentation Link. Run './scripts update-docs-links'"
    severity: error

  russian_docstring:
    name: "Russian Docstring"
    regex: '^\s*///\s+(?![^а-яА-ЯёЁ\n]*[а-яА-ЯёЁ])(?!(?:\s*(?:NOTE:|JSON|http|https| - | -|---|```|`|\[|\{|\}|\(|\)|\]|"|:|\d+pt|- Parameters:|- Returns:|- Throws:))).+'
    message: "Documentation (Docstring) must be in Russian"
    severity: error

  # =====================================================
  # TESTING RULES - Enforcing tx-mobile best practices
  # =====================================================

  # Правило: UI тест класс должен содержать ровно ОДНУ функцию test()
  # Применяется только к UI тестам (файлы содержащие BaseTestCase, но не сам BaseTestCase)
  ui_test_single_test_function:
    name: "UI Test must have exactly one test function"
    regex: 'BaseTestCase.*\n.*func\s+test.*\n.*func\s+test'
    message: "UI test class must contain exactly one test function (1 class = 1 test)"
    severity: error
    excluded: "BaseTestCase"

  test_configuration_builder:
    name: "Test configuration should use fluent API"
    regex: '(?<!URLSession)configuration\s*\.\w+\s*=\s*(?!configuration\s*\.\w+)'
    message: "Use configuration.set() fluent API pattern instead of direct assignment"
    severity: error

  test_fluent_return:
    name: "Test methods should return Self for chaining"
    regex: '@discardableResult\s+func\s+\w+\([^)]*\)\s*(?:async\s*)?->\s*\w+Steps\s*\{'
    message: "Test step methods should return Self for fluent chaining"
    severity: error

  test_step_xctcontext:
    name: "Test steps should use XCTContext.runActivity"
    regex: 'func\s+test\([^)]*\)\s*throws\s*\{[^}]*(?:func\s+step\()'
    message: "Test steps should be wrapped in XCTContext.runActivity for better logging"
    severity: error

  test_assertion_message:
    name: "Assertions require descriptive messages"
    regex: 'XCTAssert(?:Equal|NotEqual|True|False|Nil|NotNil)\([^,]+,\s*file:\s*#file'
    message: "Assertion should include descriptive message as first parameter"
    severity: error

  # Применяется только к UITests директории
  test_page_object_naming:
    name: "Page Object screens must use UT prefix"
    regex: 'class\s+\w+(?:Screen|Page)\s*:\s*(?:UTElement|UTBaseScreen)'
    message: "Page Object classes must use UT prefix (e.g., UTLoginScreen extends UTElement)"
    severity: error

  # Применяется только к UITests директории
  test_element_naming:
    name: "Test elements must use UT prefix"
    regex: 'class\s+(?!UT)[A-Z]\w+(?:Button|Field|Input|Cell|Row|Tab|Bar|Sheet|Alert|Chip)\s*:\s*UTElement'
    message: "Test element classes must use UT prefix (e.g., UTButton extends UTElement)"
    severity: error

  test_constants_centralized:
    name: "Test data should use centralized constants"
    regex: '(?:let|var)\s+\w+(?:Login|Password|Pin|Ticker|Account)[^:]+\s*=\s*"[^"]+"'
    message: "Use centralized test constants instead of inline strings"
    severity: error

  test_wait_for_existence:
    name: "Use waitForExistence instead of exists check in loops"
    regex: 'while\s+\w+\.exists\s*\{[^}]*sleep'
    message: "Use element.waitForExistence() instead of polling with sleep"
    severity: error

  test_no_hardcoded_timeout:
    name: "No hardcoded timeout values in tests"
    regex: '\.waitForExistence\(timeout:\s*([1-9][0-9]?|)\s*\)'
    message: "Use elementTimeout constant instead of hardcoded values"
    severity: error

  test_launch_environment:
    name: "Launch environment should use constants"
    regex: 'launchEnvironment\["[^"]+"\]\s*=\s*"[^"]+"'
    message: "Define environment keys as constants in a centralized configuration"
    severity: error

  no_direct_padding:
    name: "No direct padding"
    regex: '\.padding\(\s*(\.[a-z]+\s*,\s*)?[0-9]+'
    message: "Use AppSpacing constants instead of magic numbers in .padding()"
    severity: error

  no_direct_font:
    name: "No direct font"
    regex: '\.font\(\s*\.(system\(size:\s*\d+|largeTitle|title|title2|title3|headline|subheadline|body|callout|footnote|caption|caption2)\)'
    message: "Use AppTypography constants instead of direct .font() calls"
    severity: error

included:
  - App
  - Features
  - Models
  - Views
  - ViewModels
  - Services
  - Data
  - Core
  - Design
  - Tools/Scripts
  - ChatTests
  - ChatUITests

excluded:
  - Chat.xcodeproj
  - Resources
  - Design/Generated
  - Tools/Scripts/.build
  - .build
  - build/
  - chatbuild/

analyzer_rules:
  - unused_import
  - unused_declaration
