# MARK: - Связь с документацией: Документация проекта (Версия: 1.0.0). Статус: Синхронизировано.
disabled_rules: []

opt_in_rules:
  - empty_count
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - modifier_order
  - redundant_nil_coalescing
  - vertical_whitespace_closing_braces
  - line_length
  - cyclomatic_complexity
  - missing_docs
  - file_name

line_length: 160

file_name:
  excluded:
    - CLI.swift
    - Colors.swift
    - Spacing.swift
    - Typography.swift
    - ComponentConstants.swift
    - PrimaryButtonStyle.swift
    - Package.swift
    - Shell.swift
    - Metrics.swift
    - ExceptionRegistry.swift
    - Versions.swift
    - ProjectChecker.swift
    - DownloadDocs.swift
    - UpdateDocsLinks.swift
    - Check.swift
    - Ship.swift
    - ConfigureSudo.swift
    - Setup.swift
    - UITestModule.swift

identifier_name:
  min_length: 2
  excluded:
    - id

custom_rules:
  no_direct_color_use:
    name: "No direct color use"
    regex: 'Color\(\.[a-zA-Z]+\)'
    message: "Use AppColors or SwiftGen constants instead of direct Color extensions"
    severity: warning

  no_print_logger:
    name: "No print()"
    # Запрещаем print(), кроме строк содержащих разрешенные контексты (#Preview | Logger | metrics.csv)
    regex: '^(?!.*(#Preview|Logger|metrics\.csv)).*print\('
    message: "Use Logger (Pulse) instead of print(); allowed only in #Preview, Logger proxy calls, or metrics.csv writes"
    severity: warning
    excluded: "Tools/Scripts/.*"

  viewmodel_main_actor:
    name: "ViewModel MainActor"
    regex: '(?m)\A(?![\s\S]*@MainActor)[\s\S]*class\s+\w+ViewModel'
    message: "ViewModel classes must be marked with @MainActor"
    severity: error

  doc_link_required:
    name: "Missing Doc Link"
    regex: '(?m)\A(?![\s\S]*MARK: - Связь с документацией:)'
    message: "Missing Documentation Link. Run './scripts update-docs-links'"
    severity: error

  russian_docstring:
    name: "Russian Docstring"
    regex: '^\s*///\s+(?![^а-яА-ЯёЁ\n]*[а-яА-ЯёЁ])(?!(?:\s*(?:NOTE:|JSON|http|https| - | -|---|```|`|\[|\{|\}|\(|\)|\]|"|:|\d+pt|- Parameters:|- Returns:|- Throws:))).+'
    message: "Documentation (Docstring) must be in Russian"
    severity: warning

  no_direct_padding:
    name: "No direct padding"
    regex: '\.padding\(\s*(\.[a-z]+\s*,\s*)?[0-9]+'
    message: "Use AppSpacing constants instead of magic numbers in .padding()"
    severity: warning

  no_direct_font:
    name: "No direct font"
    regex: '\.font\(\s*\.(system\(size:\s*\d+|largeTitle|title|title2|title3|headline|subheadline|body|callout|footnote|caption|caption2)\)'
    message: "Use AppTypography constants instead of direct .font() calls"
    severity: warning

included:
  - App
  - Features
  - Models
  - Views
  - ViewModels
  - Services
  - Data
  - Core
  - Design
  - Tools/Scripts

excluded:
  - Chat.xcodeproj
  - Resources
  - Design/Generated
  - Tools/Scripts/.build
  - .build
  - build/
  - chatbuild/

analyzer_rules:
  - unused_import
  - unused_declaration
