name: Chat
options:
  bundleIdPrefix: ru.nearbe
  deploymentTarget:
    iOS: "26.2"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    IPHONEOS_DEPLOYMENT_TARGET: "26.2"
    TARGETED_DEVICE_FAMILY: "1"
    DEVELOPMENT_TEAM: QP3VV6YM6A
    CODE_SIGN_STYLE: Automatic
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"

targets:
  Chat:
    type: application
    platform: iOS
    sources:
      - path: ChatApp.swift
      - path: Models
      - path: Views
      - path: ViewModels
      - path: Services
      - path: Data
      - path: Utils
      - path: Design
      - path: Resources
      - path: Resources/Settings.bundle
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ru.nearbe.chat
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
        SWIFT_EMIT_LOC_STRINGS: "YES"
        CODE_SIGN_ENTITLEMENTS: Resources/Chat.entitlements
        CODE_SIGN_IDENTITY: "iPhone Developer"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: "NO"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: "NO"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: "NO"
    entitlements:
      path: Resources/Chat.entitlements
      properties:
        com.apple.security.app-sandbox: false
    info:
      path: Resources/Info.plist
      properties:
        CFBundleName: Chat
        CFBundleDisplayName: Sexy
        CFBundleIdentifier: ru.nearbe.chat
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: Chat
        CFBundleDisplayName: Sexy
        LSApplicationCategoryType: "public.app-category.productivity"
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true

schemes:
  Chat:
    build:
      targets:
        Chat: all
    run:
      config: Debug
    archive:
      config: Release
