# См. документацию: Docs/Codegen/XcodeGen/README.md
name: Chat
options:
  bundleIdPrefix: ru.nearbe
  deploymentTarget:
    iOS: "26.2"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  Factory:
    url: https://github.com/hmlongco/Factory.git
    from: 2.3.0
  Pulse:
    url: https://github.com/kean/Pulse.git
    from: 4.0.0
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing.git
    from: 1.15.4
  Scripts:
    path: Tools/Scripts

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_TREAT_WARNINGS_AS_ERRORS: YES
    GCC_TREAT_WARNINGS_AS_ERRORS: YES
    IPHONEOS_DEPLOYMENT_TARGET: "26.2"
    TARGETED_DEVICE_FAMILY: "1"
    DEVELOPMENT_TEAM: QP3VV6YM6A
    CODE_SIGN_STYLE: Automatic
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"

targets:
  Chat:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Features
      - path: Models
      - path: Services
      - path: Data
      - path: Core
      - path: Design
      - path: Resources
      - path: ProjectTests.xctestplan
      - path: Resources/Settings.bundle
        buildPhase: resources
    dependencies:
      - package: Factory
      - package: Pulse
        product: Pulse
      - package: Pulse
        product: PulseUI
    postBuildScripts:
      - name: SwiftLint
        script: |
          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        basedOnDependencyAnalysis: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ru.nearbe.chat
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
        SWIFT_EMIT_LOC_STRINGS: "YES"
        CODE_SIGN_ENTITLEMENTS: Resources/Chat.entitlements
        CODE_SIGN_IDENTITY: "iPhone Developer"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: "NO"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: "NO"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: "NO"
    entitlements:
      path: Resources/Chat.entitlements
      properties:
        com.apple.security.app-sandbox: false
    info:
      path: Resources/Info.plist
      properties:
        CFBundleName: Chat
        CFBundleIdentifier: ru.nearbe.chat
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: Chat
        CFBundleDisplayName: Sexy
        LSApplicationCategoryType: "public.app-category.productivity"
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true

  ChatTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ChatTests
    dependencies:
      - target: Chat
      - package: SnapshotTesting
        product: SnapshotTesting
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

  ChatUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: ChatUITests
    dependencies:
      - target: Chat
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

schemes:
  Chat:
    build:
      targets:
        Chat: all
        ChatTests: [test]
        ChatUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      testPlans:
        - path: ProjectTests.xctestplan
          defaultPlan: true
    archive:
      config: Release
