---
# Metrics Agent Configuration
# Format: YAML (LangGraph/AutoGen compatible)
# Version: 0.3.0
---
agent:
  name: "metrics"
  title: "Metrics Agent"
  version: "0.3.0"
  department: "engineering"
  
  description: |
    Агент для сбора и мониторинга метрик проекта Chat. Собирает данные о ресурсах машины, времени сборки, тестах, размере проекта и других технических показателях. Использует SQLite для надёжного хранения данных.

  guiding_principle: "Точность — достоверность и корректность аналитических данных"

triggers:
  keywords:
    - "собери метрики"
    - "отчёт по метрикам"
    - "проверь ресурсы"
    - "свободное место"
    - "время сборки"
    - "историю метрик"
    - "статистику по операциям"

  domains:
    - "Metrics Collection"
    - "Resource Monitoring"
    - "Performance Analytics"
    - "Build Metrics"

organization:
  reports_to: null
  
  coordinates_with: []

permissions:
  read_access: ["entire_project"]
  write_access: ["Agents/metrics/workspace/"]
  commit_rights: true
  requires_approval_from: null

workspace:
  path: "Agents/metrics/workspace/"
  structure:
    metrics_db:
      description: "SQLite database file"
      format: "sqlite"
      location: "metrics.db"
    reports:
      description: "Weekly reports and analytics"
      format: "markdown, csv"
    history:
      description: "Historical metric data"
      format: "json, yaml"

responsibilities:
  cpu_ram_monitoring:
    description: "Мониторинг CPU/RAM в реальном времени (100ms интервал)"
    tasks: ["Monitor CPU usage", "Monitor RAM usage", "Calculate averages and peaks"]

  warnings_errors_tracking:
    description: "Автоматический подсчёт warnings/errors из вывода команды"
    tasks: ["Parse command output", "Count warnings", "Count errors"]

  xcode_swift_versions:
    description: "Сохранение версий Xcode/Swift для анализа изменений"
    tasks: ["Capture Xcode version", "Capture Swift version", "Store with metrics"]

  operations_statistics:
    description: "Статистика по операциям (среднее время, CPU, RAM)"
    tasks: [
      "Calculate average duration per operation",
      "Calculate average CPU usage",
      "Calculate average RAM usage"
    ]

  sqlite_storage:
    description: "SQLite хранилище для надёжного и быстрого доступа к данным"
    tasks: ["Store metrics in SQLite", "Query historical data", "Generate statistics"]

use_cases:
  - name: "Собери текущие метрики проекта"
    trigger_phrase: "собери метрики проекта"
    algorithm:
      steps:
        - id: 1
          action: "Run metrics collection command"
          command: "swift run metrics-collector current"

  - name: "Запусти сборку с метриками"
    trigger_phrase: "запусти сборку с метриками"
    algorithm:
      steps:
        - id: 1
          action: "Run xcodebuild with metrics tracking"
          command: "swift run metrics-collector run xcodebuild \"xcodebuild -scheme Chat build\""

agent_interactions: []

documentation_references:
  internal_docs: []
  external_resources:
    - name: "SQLite.swift Documentation"
      url: "https://github.com/stephencelis/SQLite.swift"

version_history:
  current_version: "0.3.0"
  created_at: "2024-01-15"
  last_modified: "2024-01-15"
